feat: # 0000 - test

diff --git a/.github/workflows/cicd_pipeline.yml b/.github/workflows/cicd_pipeline.yml
--- a/.github/workflows/cicd_pipeline.yml
+++ b/.github/workflows/cicd_pipeline.yml
@@ -33,16 +33,16 @@ jobs:
       - name: convention checker
         id: pr_title_check
         run: |
-          message=$(jq -r '.pull_request.body // empty' "$GITHUB_EVENT_PATH")
-          echo "PR message: $message"  # Debugging output
+          title=$(jq -r '.pull_request.body // empty' "$GITHUB_EVENT_PATH")
+          echo "PR title: $title"  # Debugging output
           
-          if [[ -z "$message" ]]; then
-            echo "PR message is empty or not found."
+          if [[ -z "$title" ]]; then
+            echo "PR title is empty or not found."
             exit 1
           fi
           
-          if ! [[ "$message" =~ ^(fix|feat|chore|docs|refactor|style|test): #[0-9]+ - .+$ ]]; then
-            echo "PR message does not match the required format 'fix|feat|chore|docs|refactor|style|test: #0000 - description'."
+          if ! [[ "$title" =~ ^(fix|feat|chore|docs|refactor|style|test): #[0-9]+ - .+$ ]]; then
+            echo "PR title does not match the required format 'fix|feat|chore|docs|refactor|style|test: #0000 - description'."
             exit 1
           fi
           
