fix: #0000 - made changes

diff --git a/.github/workflows/cicd_pipeline.yml b/.github/workflows/cicd_pipeline.yml
--- a/.github/workflows/cicd_pipeline.yml
+++ b/.github/workflows/cicd_pipeline.yml
@@ -33,12 +33,9 @@ jobs:
       - name: convention checker
         id: pr_title_check
         run: |
-          title=$(jq -r '.pull_request.title' "$GITHUB_EVENT_PATH")
-          echo "PR Title: $title"  # Debugging output
-
-          # Conditional check for PR title format
-          if ! [[ "$title" =~ ^(fix|feat|chore|docs|refactor|style|test): #[0-9]+ - .+$ ]]; then
-            echo "PR title does not match the required format 'fix|feat|chore|docs|refactor|style|test: #0000 - description'."
+          message=$(jq -r '.pull_request.body' "$GITHUB_EVENT_PATH")
+          if ! [[ "$message" =~ ^(fix|feat|chore|docs|refactor|style|test): #[0-9]+ - .+$ ]]; then
+            echo "PR message does not match the required format 'fix|feat|chore|docs|refactor|style|test: #0000 - description'."
             exit 1
           fi
           
